CREATE TABLE transcript_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_name TEXT NOT NULL,
    youtube_url TEXT NOT NULL,
    video_id TEXT NOT NULL UNIQUE,
    transcription TEXT NOT NULL,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL
);

CREATE INDEX transcript_entries_updated_at_id_idx
    ON transcript_entries (updated_at DESC, id DESC);
