/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated.index'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated.history'
import { Route as AuthenticatedUploadRouteImport } from './routes/_authenticated.upload'
import { Route as ShoesIndexRouteImport } from './routes/shoes.index'
import { Route as ShoesShoeIdRouteImport } from './routes/shoes.$shoeId'
import { Route as AuthenticatedAdminTranscriptsRouteImport } from './routes/_authenticated.admin.transcripts'
import { Route as AuthenticatedExtractionsIdRouteImport } from './routes/_authenticated.extractions.$id'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUploadRoute = AuthenticatedUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ShoesIndexRoute = ShoesIndexRouteImport.update({
  id: '/shoes/',
  path: '/shoes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShoesShoeIdRoute = ShoesShoeIdRouteImport.update({
  id: '/shoes/$shoeId',
  path: '/shoes/$shoeId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminTranscriptsRoute =
  AuthenticatedAdminTranscriptsRouteImport.update({
    id: '/admin/transcripts',
    path: '/admin/transcripts',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedExtractionsIdRoute =
  AuthenticatedExtractionsIdRouteImport.update({
    id: '/extractions/$id',
    path: '/extractions/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/upload': typeof AuthenticatedUploadRoute
  '/shoes/$shoeId': typeof ShoesShoeIdRoute
  '/shoes/': typeof ShoesIndexRoute
  '/admin/transcripts': typeof AuthenticatedAdminTranscriptsRoute
  '/extractions/$id': typeof AuthenticatedExtractionsIdRoute
}
export interface FileRoutesByTo {
  '/history': typeof AuthenticatedHistoryRoute
  '/upload': typeof AuthenticatedUploadRoute
  '/shoes/$shoeId': typeof ShoesShoeIdRoute
  '/': typeof AuthenticatedIndexRoute
  '/shoes': typeof ShoesIndexRoute
  '/admin/transcripts': typeof AuthenticatedAdminTranscriptsRoute
  '/extractions/$id': typeof AuthenticatedExtractionsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/upload': typeof AuthenticatedUploadRoute
  '/shoes/$shoeId': typeof ShoesShoeIdRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/shoes/': typeof ShoesIndexRoute
  '/_authenticated/admin/transcripts': typeof AuthenticatedAdminTranscriptsRoute
  '/_authenticated/extractions/$id': typeof AuthenticatedExtractionsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/history'
    | '/upload'
    | '/shoes/$shoeId'
    | '/shoes/'
    | '/admin/transcripts'
    | '/extractions/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/history'
    | '/upload'
    | '/shoes/$shoeId'
    | '/'
    | '/shoes'
    | '/admin/transcripts'
    | '/extractions/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/history'
    | '/_authenticated/upload'
    | '/shoes/$shoeId'
    | '/_authenticated/'
    | '/shoes/'
    | '/_authenticated/admin/transcripts'
    | '/_authenticated/extractions/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ShoesShoeIdRoute: typeof ShoesShoeIdRoute
  ShoesIndexRoute: typeof ShoesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/upload': {
      id: '/_authenticated/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof AuthenticatedUploadRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/shoes/': {
      id: '/shoes/'
      path: '/shoes'
      fullPath: '/shoes/'
      preLoaderRoute: typeof ShoesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shoes/$shoeId': {
      id: '/shoes/$shoeId'
      path: '/shoes/$shoeId'
      fullPath: '/shoes/$shoeId'
      preLoaderRoute: typeof ShoesShoeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/transcripts': {
      id: '/_authenticated/admin/transcripts'
      path: '/admin/transcripts'
      fullPath: '/admin/transcripts'
      preLoaderRoute: typeof AuthenticatedAdminTranscriptsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/extractions/$id': {
      id: '/_authenticated/extractions/$id'
      path: '/extractions/$id'
      fullPath: '/extractions/$id'
      preLoaderRoute: typeof AuthenticatedExtractionsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedUploadRoute: typeof AuthenticatedUploadRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAdminTranscriptsRoute: typeof AuthenticatedAdminTranscriptsRoute
  AuthenticatedExtractionsIdRoute: typeof AuthenticatedExtractionsIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedUploadRoute: AuthenticatedUploadRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAdminTranscriptsRoute: AuthenticatedAdminTranscriptsRoute,
  AuthenticatedExtractionsIdRoute: AuthenticatedExtractionsIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ShoesShoeIdRoute: ShoesShoeIdRoute,
  ShoesIndexRoute: ShoesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
